### ISSUE TITLE
Check for reserved keywords in entry IDs

### ISSUE THREAD

**Issue by niekdt** [niekdt/actionsheets#10]
Currently, using some of the reserved entry IDs results in unintuitive errors much later in the processing chain.

Example:
```toml
[format.link.source]
action = "Specify source"
code = "@source This dataset was generated using [generateData]"
```

conflicts with the `source` field
